"""add_reconciliation_tables

Revision ID: 1529eae5abf6
Revises: a1b2c3d4e5f6
Create Date: 2026-08-13 22:06:30.925704+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1529eae5abf6"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reconciliation_jobs",
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("total_wallets_checked", sa.Integer(), nullable=False),
        sa.Column("discrepancies_found", sa.Integer(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reconciliation_discrepancies",
        sa.Column("job_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("wallet_id", sa.String(length=36), nullable=False),
        sa.Column("expected_balance", sa.BigInteger(), nullable=False),
        sa.Column("actual_balance", sa.BigInteger(), nullable=False),
        sa.Column("difference", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["reconciliation_jobs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reconciliation_discrepancies_job_id"),
        "reconciliation_discrepancies",
        ["job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reconciliation_discrepancies_wallet_id"),
        "reconciliation_discrepancies",
        ["wallet_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_reconciliation_discrepancies_wallet_id"),
        table_name="reconciliation_discrepancies",
    )
    op.drop_index(
        op.f("ix_reconciliation_discrepancies_job_id"),
        table_name="reconciliation_discrepancies",
    )
    op.drop_table("reconciliation_discrepancies")
    op.drop_table("reconciliation_jobs")
    # ### end Alembic commands ###
